travis:
  secure:
    BINSTAR_TOKEN: AQEpO0uTCDNsEd3SFzcCICV6CjEKB0JXCqYXjUdB3r5Q/58m2XHu5VxNGijY19ZzRQtNUkuH7Pxd692E8ktR9x+1GjPDo2Ivr858xl0aWk6cWEbPFVQ7PK6kkLQStpcw44HRDCaW8wKi5+sEH7xYlfdbY8OY2/YnCIhDz691yzED5E9qgTx7BGpux7MO2dhEu1G/Iex5dDP6LCEw3LLlgSJeWHy+XEVEe9HkL8yS5cBpWgT0gVtBZC0h3vKkuX5gsmbebi8Lnkqq+Hf6TwWpM+be18VOvlP507ZwssNjfesUvfVDAKuzh4bi6Cyb7kinVBpN6TC5fodrCN73yqn6HIAr9Z+kWD9T/LTiT4vfHuRa5WZBFCo+vnglko+Y5o3FsYphKI6Mde6wghjFn4bBhmqPcYVPUX9OoTrFlzwXBxTEKR63lGs9IRt8c+YYybwhFHMHnopavgwIjWLJT57fOrNzzSd/gqK71YA4jxd1KrAsNiFeipLswhXToJcG6/KYNal6mKqJK+J5gCghaUMLaf9wwtUo9RBMKiZXl2zmyko+4n+k9p40OwS+qrkVyErYkI7gZ1Le2Gh3irIOBztQTvOworuPLp9kTRhfcSvUf9IGGBfOIXFiF790ijo5T759o2iigBE4BYALfGDGqwWWEY9FnQuzp/Qi0VeS8+1DqIc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
